// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: comments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
    content,
    post_id,
    user_id,
    parent_id
) VALUES (
    $1, $2, $3, $4
) RETURNING id, content, post_id, user_id, parent_id, created_at
`

type CreateCommentParams struct {
	Content  string      `json:"content"`
	PostID   pgtype.UUID `json:"post_id"`
	UserID   pgtype.UUID `json:"user_id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.Content,
		arg.PostID,
		arg.UserID,
		arg.ParentID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.PostID,
		&i.UserID,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1 AND user_id = $2
`

type DeleteCommentParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.Exec(ctx, deleteComment, arg.ID, arg.UserID)
	return err
}

const getComment = `-- name: GetComment :one
SELECT 
    c.id, c.content, c.post_id, c.user_id, c.parent_id, c.created_at,
    u.username as author_name
FROM comments c
LEFT JOIN users u ON c.user_id = u.id
WHERE c.id = $1
`

type GetCommentRow struct {
	ID         uuid.UUID          `json:"id"`
	Content    string             `json:"content"`
	PostID     pgtype.UUID        `json:"post_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ParentID   pgtype.UUID        `json:"parent_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	AuthorName pgtype.Text        `json:"author_name"`
}

func (q *Queries) GetComment(ctx context.Context, id uuid.UUID) (GetCommentRow, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i GetCommentRow
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.PostID,
		&i.UserID,
		&i.ParentID,
		&i.CreatedAt,
		&i.AuthorName,
	)
	return i, err
}

const listCommentsByPost = `-- name: ListCommentsByPost :many
SELECT 
    c.id, c.content, c.post_id, c.user_id, c.parent_id, c.created_at,
    u.username as author_name
FROM comments c
LEFT JOIN users u ON c.user_id = u.id
WHERE c.post_id = $1
ORDER BY c.created_at DESC
`

type ListCommentsByPostRow struct {
	ID         uuid.UUID          `json:"id"`
	Content    string             `json:"content"`
	PostID     pgtype.UUID        `json:"post_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ParentID   pgtype.UUID        `json:"parent_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	AuthorName pgtype.Text        `json:"author_name"`
}

func (q *Queries) ListCommentsByPost(ctx context.Context, postID pgtype.UUID) ([]ListCommentsByPostRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByPostRow{}
	for rows.Next() {
		var i ListCommentsByPostRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.PostID,
			&i.UserID,
			&i.ParentID,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
